### ISSUE TITLE
Error "Some parameters are out of range" for some coordinates

### ISSUE THREAD

**Issue by leoribg** [Cloud-RF/Signal-Server#15]
I have some coordinates which give me this error and I can't find why. Used both SRTM1 and SRTM3 datas and gave me the same error for both. Changing the coordinates a little, like 300m, seems to fix the problem but this is happening for a lot of points.
Here are the coordinates:
Tx
-25.539973517
49.197435959
3m

Rx
-25.534975575
49.200645038
3m

**Comment by Cloud-RF** [comment]
As discussed in email, this is SPLAT! 1.4.2 you are using and Signal-Server did not have an issue with this path.
