### ISSUE TITLE
Propagation calculation does not seem to be done

### ISSUE THREAD

**Issue by pierreduf** [Cloud-RF/Signal-Server#16]
I don't manage to get Signal Server working : it built perfectly without any errors but I never get a color map with RSSI levels.

* Height data is OK : I've downloaded SRTM1 and SRTM3 to be sure, converted them with srtm2sdf and I see the correct topograhy map in greyscale with the "-t" option
* When I enable debug ( -dbg) I see that height data are correctly loaded, there a no errors
* I've tried multiple calculations at different places, including the one in the Readme
* I've tried to put very high height for Rx and Tx to see if the Tx or Rx were not "buried" in the ground (in case height were not in AGL but above sea)
* I've tried with and without height data : in such a case there's the "consider sea level" warning in the debug output and the "greyscale" output is always blue
* I've tried to put different and very high ERPs
* I've tried with and without antenna file (from what I've understood in the code, if there's no antenna pattern file everything is filled with a unit gain)
* I've tried multiple propagation models (1, 2 and 3)

I always a get a perfectly blank ppm (or the greyscale topology if enabled) except sometimes (I need to confirm with what set of parameters) when I have only 1 pixel wide line of calculation (see attached file, in that case I launched it without any height data)

Any idea of what I could have done wrong or how I could debug that ?

Thanks a lot for your help !

![test1](https://user-images.githubusercontent.com/4528088/42105236-e91bf62e-7bcf-11e8-8fc4-e0e66b3a886e.png)

**Comment by Cloud-RF** [comment]
Can you show the full command you used please.

**Comment by pierreduf** [comment]
The two from the Readme : 

`../signalserverHD -sdf ../data/SRTM1 -lat 51.849 -lon -2.2299 -txh 25 -f 450 -erp 20 -rxh 2 -rt 10 -o test2 -R 10 -res 3600 -pm 3`

`../signalserver -sdf ../data/SRTM3 -lat 51.849 -lon -2.2299 -txh 25 -f 900 -erp 5 -rxh 2 -rt -90 -dbm -m -o test1 -R 30 -res 1200 -pm 1`

The paths are adapted to fit my configuration. As the height maps were loaded I guess that the path relativity (and not being absolute) are not important

At last the picture with the "line" was produced with : 

`../signalserver -sdf ../data/SRTM3 -lat 51.849 -lon 1.000 -txh 25 -f 900 -erp 5 -rxh 2 -rt -90 -dbm -m -o test2 -R 30 -res 1200 -pm 1 -dbg`

So there seems to be a difference before and after greenwich but I don't know why (nothing at all in a case and just a line the other case)

**Comment by Cloud-RF** [comment]
I don't have the same issue with those commands on Ubuntu Linux. Can you share your debug output and OS.

**Comment by pierreduf** [comment]
Thank you for your answer.

I'll get you the whole output tomorrow when I have access to the machine. The OS is Centos7.

Do you have any idea where that could come from ? Have you already seen that ? Is there a way to enable more debug logs in your code ?

**Comment by pierreduf** [comment]
The OS information: 

`Linux localhost.localdomain 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

```
   Static hostname: localhost.localdomain
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: 1399b75f89a84a71ba47895005558db1
           Boot ID: 9f1e265f941b4038839c652256211255
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-862.3.2.el7.x86_64
      Architecture: x86-64
```

The full output is below 

```
[xxxxxx@localhost export]$ ../signalserver -sdf ../data/SRTM3 -lat 51.849 -lon 1.0 -txh 25 -f 900 -erp 5 -rxh 500 -dbm -m -o test1 -R 30 -res 1200 -pm 1 -dbg
-90.0000,360.0000,90.0000,-1.0000,0.0000,361.0001
Loading "../data/SRTM3/51:52:359:0.sdf" into page 1...
Loading "../data/SRTM3/51:52:0:1.sdf" into page 2...
Loading "../data/SRTM3/51:52:1:2.sdf" into page 3...
Loading "../data/SRTM3/51:52:2:3.sdf" into page 4...
Loading "../data/SRTM3/51:52:358:359.sdf" into page 5...
Loading "../data/SRTM3/52:53:358:359.sdf" into page 6...
Loading "../data/SRTM3/52:53:359:0.sdf" into page 7...
signal power level contours of "Tx"
out to a radius of 30.00 kilometers with Rx antenna(s) at 500.00 meters AGL
Finished PlotPropagation()
Cropping 1: max_west: 359.4375 cropLat: 0.2705 cropLon: 0.4375 longitude: 359.00000 dpp 0.0008333
Cropping 2: max_west: 359.4375 cropLat: 0.2705 cropLon: 0.4375000 longitude: 359.00000 width 1050

Writing "test1.ppm" (1050x649 pixmap image)...
|52.119479|1.437500|51.578521|0.562500|

[xxxxxx@localhost export]$ convert test1.ppm test1.png
```
When I add the `-t` option I got the same log output with the following output picture :

![with_line_with_topo](https://user-images.githubusercontent.com/4528088/42151606-caa72c80-7ddd-11e8-9a2e-b2a37599eedc.png)

I've noticed that if the output files (.ppm / .dcf ?) are already present in the directory, I've got more logs (`LoadDBMColors()`). Is that normal ?

```
[xxxxx@localhost export]$ ../signalserver -sdf ../data/SRTM3 -lat 51.849 -lon 1.0 -txh 25 -f 900 -erp 5 -rxh 500 -dbm -m -o test1 -R 30 -res 1200 -pm 1 -dbg -t
-90.0000,360.0000,90.0000,-1.0000,0.0000,361.0001
Loading "../data/SRTM3/51:52:359:0.sdf" into page 1...
Loading "../data/SRTM3/51:52:0:1.sdf" into page 2...
Loading "../data/SRTM3/51:52:1:2.sdf" into page 3...
Loading "../data/SRTM3/51:52:2:3.sdf" into page 4...
Loading "../data/SRTM3/51:52:358:359.sdf" into page 5...
Loading "../data/SRTM3/52:53:358:359.sdf" into page 6...
Loading "../data/SRTM3/52:53:359:0.sdf" into page 7...
signal power level contours of "Tx"
out to a radius of 30.00 kilometers with Rx antenna(s) at 500.00 meters AGL
Finished PlotPropagation()
Cropping 1: max_west: 359.4375 cropLat: 0.2705 cropLon: 0.4375 longitude: 359.00000 dpp 0.0008333
Cropping 2: max_west: 359.4375 cropLat: 0.2705 cropLon: 0.4375000 longitude: 359.00000 width 1050

LoadDBMColors() 0: 255, 0, 0

LoadDBMColors() -10: 255, 128, 0

LoadDBMColors() -20: 255, 165, 0

LoadDBMColors() -30: 255, 206, 0

LoadDBMColors() -40: 255, 255, 0

LoadDBMColors() -50: 184, 255, 0

LoadDBMColors() -60: 0, 255, 0

LoadDBMColors() -70: 0, 208, 0

LoadDBMColors() -80: 0, 196, 196

LoadDBMColors() -90: 0, 148, 255

LoadDBMColors() -100: 80, 80, 255

LoadDBMColors() -110: 0, 38, 255

LoadDBMColors() -120: 142, 63, 255

LoadDBMColors() -130: 196, 54, 255

LoadDBMColors() -140: 255, 0, 255

LoadDBMColors() -150: 255, 194, 204

Writing "test1.ppm" (1050x649 pixmap image)...
|52.119479|1.437500|51.578521|0.562500|
[xxxxx@localhost export]$ convert test1.ppm test1.png
```

**Comment by pierreduf** [comment]
Sorry, I've left a very high Rx height fo testing. With a typical 1.5 meters I've got roughly the same result (but the line is pinky instead of bluish):

```
[xxxxxxx@localhost export]$ ../signalserver -sdf ../data/SRTM3 -lat 51.849 -lon 1.0 -txh 25 -f 900 -erp 1 -rxh 1.5 -dbm -m -o test1 -R 30 -res 1200 -pm 1 -dbg -t
-90.0000,360.0000,90.0000,-1.0000,0.0000,361.0001
Loading "../data/SRTM3/51:52:359:0.sdf" into page 1...
Loading "../data/SRTM3/51:52:0:1.sdf" into page 2...
Loading "../data/SRTM3/51:52:1:2.sdf" into page 3...
Loading "../data/SRTM3/51:52:2:3.sdf" into page 4...
Loading "../data/SRTM3/51:52:358:359.sdf" into page 5...
Loading "../data/SRTM3/52:53:358:359.sdf" into page 6...
Loading "../data/SRTM3/52:53:359:0.sdf" into page 7...
signal power level contours of "Tx"
out to a radius of 30.00 kilometers with Rx antenna(s) at 1.50 meters AGL
Finished PlotPropagation()
Cropping 1: max_west: 359.4375 cropLat: 0.2705 cropLon: 0.4375 longitude: 359.00000 dpp 0.0008333
Cropping 2: max_west: 359.4375 cropLat: 0.2705 cropLon: 0.4375000 longitude: 359.00000 width 1050

Writing "test1.ppm" (1050x649 pixmap image)...
|52.119479|1.437500|51.578521|0.562500|
[xxxxxx@localhost export]$ convert test1.ppm test1.png
```

![test1](https://user-images.githubusercontent.com/4528088/42151896-c275db8c-7dde-11e8-92b1-7f72f3ef29bd.png)

**Comment by pierreduf** [comment]
At last, with the following command: 

`../signalserver -sdf ../data/SRTM3 -lat 51.849 -lon -2.2299 -txh 25 -f 900 -erp 5 -rxh 2 -rt -90 -dbm -m -o test2 -R 30 -res 1200 -pm 1 -dbg -t`

I've got:

```
[xxxxx@localhost export]$ ../signalserver -sdf ../data/SRTM3 -lat 51.849 -lon -2.2299 -txh 25 -f 900 -erp 5 -rxh 2 -rt -90 -dbm -m -o test2 -R 30 -res 1200 -pm 1 -dbg -t
-90.0000,360.0000,90.0000,-1.0000,0.0000,361.0001
Loading "../data/SRTM3/51:52:2:3.sdf" into page 1...
Loading "../data/SRTM3/51:52:3:4.sdf" into page 2...
Loading "../data/SRTM3/51:52:4:5.sdf" into page 3...
Loading "../data/SRTM3/51:52:5:6.sdf" into page 4...
Loading "../data/SRTM3/51:52:1:2.sdf" into page 5...
Loading "../data/SRTM3/52:53:1:2.sdf" into page 6...
Loading "../data/SRTM3/52:53:2:3.sdf" into page 7...
signal power level contours of "Tx"
out to a radius of 30.00 kilometers with Rx antenna(s) at 2.00 meters AGL
Finished PlotPropagation()
Cropping 1: max_west: 2.6674 cropLat: 0.2705 cropLon: 0.4375 longitude: 2.22990 dpp 0.0008333
Cropping 2: max_west: 2.6674 cropLat: 0.2705 cropLon: 0.4375000 longitude: 2.22990 width 1050

Writing "test2.ppm" (1050x649 pixmap image)...
|52.119480|-1.792400|51.578520|-2.667400|
[xxxxxx@localhost export]$ convert test2.ppm test2.png
```

And picture: 

![test2](https://user-images.githubusercontent.com/4528088/42152148-94145e52-7ddf-11e8-9be4-1b30bf2777c4.png)

So I've got the feeling that the "line" is drawn if we are east of greenwhich (positive longitude value) but not if we are west. I don't know if makes any sense.

**Comment by pierreduf** [comment]
I tested on an Ubuntu 16.04 machine with the same results ;(.

I've also tried deactivating multi-thread (-nothreads option) but it leads to segmentation fault because of the "can_process" function (any idea why ?) :

```
Loading "../data/SRTM3/51:52:2:3.sdf" into page 1...
Loading "../data/SRTM3/51:52:3:4.sdf" into page 2...
Loading "../data/SRTM3/51:52:4:5.sdf" into page 3...
Loading "../data/SRTM3/51:52:5:6.sdf" into page 4...
signal power level contours of "Tx"
out to a radius of 5.00 kilometers with Rx antenna(s) at 2.00 meters AGL
Reading in symbols for models/los.cc...done.

Program received signal SIGSEGV, Segmentation fault.
0x0000000000419a52 in (anonymous namespace)::can_process (lat=51.849918630247302, lon=2.228513117832212) at models/los.cc:135
135                             if(!processed[indx][x][y]) {
(gdb)
```


I've made more debugging (using gdb to check variable values + adding some output logs) and it seems that most of the final value table are null (leading to a blank picture)

The workflow I observe is the following :

* DEM data are loaded : everything is fine there
* DEM data are stored in a `dem` structure (in the data 2D array)

```
struct dem {
	float min_north;
	float max_north;
	float min_west;
	float max_west;
	int max_el;
	int min_el;
	short **data;
	unsigned char **mask;
	unsigned char **signal;
};
```

* Calculation is done :
=> _PlotPropagation(tx_site[0], altitudeLR, ano_filename, propmodel, knifeedge, haf, pmenv, use_threads);_ (main.cc:1884)
=) _PlotPropagation_ is in los.cc, manage the multithreading and calls _rangePropagation(range);_ (los.cc:858)
=> then calls _PlotPropPath(v->source, edge, v->mask_value, v->fd, v->propmodel, v->knifeedge, v->pmenv);_  (los.cc:60)
=> _PlotPropPath_ calculate the attenuation on the path between Rx and Tx, using the chosen propagation model (in my cas 1: ITM)
=> calling the ITM calculation _point_to_point_ITM(...)_ (in los.cc:454)
* _point_to_point_ITM_ calculates an attenuation value and store it in `loss`
* this `loss` value is converted in `dBm` (los.cc:599), taking into account antenna again, ERP etc...then scale to 0-255 and stored in `ifs` variable
* the corresponding value at the same coordinate is read from the dem structure, stored in `ofs`, if ofs is stronger it's kept otherwise it's overwritten by `ifs`
* the signal value is stored in the dem structure by PutSignal() (los.cc:621)

At that point, I've already got a problem : I see that some values are properly calculated :

```
dBloss value: 185.2015
dBm value: -146.0718
signal value: 54
dBloss value: 168.9528
dBm value: -129.8231
signal value: 70
dBloss value: 164.8099
dBm value: -125.6802
signal value: 74
dBloss value: 185.2159
dBm value: -146.0862
signal value: 54
```

But most of my `ifs` values are null....For example only 109 non null values (for a picture with a height of 109 pxls...not a coincidence I guess)

```
ifs value: 171
ifs value: 161
ifs value: 159
ifs value: 155
[...109 non null values...]
ifs value: 89
ifs value: 94
ifs value: 97
ifs value: 84
ifs value: 172
[Thread 0x7fffeffff700 (LWP 5883) exited]
[Thread 0x7ffff5589700 (LWP 5885) exited]
[Thread 0x7ffff6b0d700 (LWP 5882) exited]
[Thread 0x7ffff5f60700 (LWP 5884) exited]
Finished PlotPropagation()
Cropping 1: max_west: 2.3032 cropLat: 0.0458 cropLon: 0.0733 longitude: 2.22990 dpp 0.0008333
Cropping 2: max_west: 2.3032 cropLat: 0.0458 cropLon: 0.0733333 longitude: 2.22990 width 176
Entering LoadDBMColors
Writing "test1.ppm" (176x109 pixmap image)...

Breakpoint 1, DoRxdPwr (Reading in symbols for main.cc...done.
filename=0x7fffffff75d0 "test1", geo=0 '\000', kml=1 '\001', ngs=1 '\001', xmtr=0x632800 <tx_site>, txsites=1 '\001') at outputs.cc:637
637                                     if (dBm >= region.level[0])
(gdb) coutn_ifs
Undefined command: "coutn_ifs".  Try "help".
(gdb) print count_ifs
$1 = 109
(gdb)
```

**Comment by pierreduf** [comment]
FYI, it's working with the latest commit from dBiTech who forked this project (https://github.com/dBitech/Signal-Server). Need to has `-ldl` to be able to build it.

I suspect something about the way the "edge" coordinates are calculated but I will look at their commits to understand the difference.

![test1](https://user-images.githubusercontent.com/4528088/42322011-0ec0bcae-805b-11e8-8512-5ddf2c62d9f6.png)

**Comment by Cloud-RF** [comment]
You're commands were absolutely right but 3.09 had a bug with loading the older SDF tiles following recent developments with high resolution ASC tiles (LIDAR). 3.10 has just been pushed. Thanks for your patience and efforts investigating this.

**Comment by pierreduf** [comment]
Great ! Thanks for you answer and reactivity !
