### ISSUE TITLE
MODIS Land cover clutter processing

### ISSUE THREAD

**Issue by pierreduf** [Cloud-RF/Signal-Server#19]
Hi,

I'm trying to use clutter data with the "clt" option and I have a few questions:

1/ Do you know where I could find a ready-to-use dataset, formatted for your program (eg. with the same resolution and size )? 

I think that's the MODIS Collection 5 format but now that the Collection 6 is out, I can't find it anywhere. Moreover, it's not already in ASCII grid format. I'm currently trying to convert a newest dataset to the right format but then the following questions arose.

2/ Why not read directly the pixel size from the ASCII grid header (see below)? Instead of:

```
	if(w==2880 && h==3840){
		cellsize=0.004167;
		cellsize2 = cellsize * 3;
```
3/ By reading the code, I've got the feeling that there's some bug below. There's an additional line reading which could cause a problem

```
	if (fgets(line, 25, fd) != NULL) {
		sscanf(pch, "%lf", &xll);
	}

	fgets(line, 25, fd);  // This read is not necessary ?

	if (fgets(line, 25, fd) != NULL) {
		sscanf(pch, "%lf", &yll);
	}
```

The ASCII grid format should be the one below. So "yll" info is just below the "xll" info, I don't see a need to make an additional line reading.

```
ncols        5398
nrows        2110
xllcorner    -108.900667860276
yllcorner    30.001075471581
cellsize     0.009478163281
```
4/ There's a resampling needed between the 500m MODIS dataset and the 30m DEM dataset (I use HD version of data). I understand that it's done by the "size" parameter of 2 used in `AddElevation(lat,lon,clh,2);` but that seems to add elevation value on a 3x3 area on the existing DEM data. As DEM resolution is 30m, 3x30=90m and we're not at the 500m source resolution. Is that normal ? Am I missing something? Even if it was for low res DEM of 90m I don't get it.

**Comment by Cloud-RF** [comment]
The MODIS 'clt' mod became obsolete several years ago when SRTM DEM (2000) which SPLAT! was built around (.sdf files) was phased out and replaced with (2014) 30m DSM (.asc files) which includes clutter so don't expect any updates there but feel free to submit a pull request from your fork.

It could certainly be improved to work with arbitrary clutter files instead of a fixed size tile but at that point you will end up re-writing the 'LIDAR' tile reader and the -lid parameter.

**Comment by pierreduf** [comment]
Hi, 

Thank you for your prompt answer ! Don't you think that would be interesting to mention it in the README ?

I wasn't aware of that 30m DSM dataset. I guess it's https://wiki.openstreetmap.org/wiki/AW3D30 ? I'll try that, thank you for the tip.

I hadn't checked the LIDAR module before because I thought it was only dedicated to specific LIDAR data but I get it now.

Anyway, when I finish the MODIS 17-class clutter integration, I'll probably send a pull request to have a clean way to use the latest MODIS Landcover data with legacy DEM data (what I tried to do until now)

**Comment by pierreduf** [comment]
I checked the precision of AW3D30 data on Paris' Roissy airport and the resolution is indeed impressive: the outline of buildings are clearly visible.

![image](https://user-images.githubusercontent.com/4528088/53565388-a81b4b80-3b59-11e9-8d5f-1c32f7e1ee0b.png)

However, do you know what's the most efficient way to use those DSM tiles instead of the legacy SRTM .hgt files.

I thought they were exactly the same: cf the output from GDAL below, same size, same pixel size, same projection etc... 

But when I use srtm2sdf (after having properly renamed them) I've got an error `Error: Premature EOF detected while reading` and the output from SignalServer is completely garbled.

```
Driver: GTiff/GeoTIFF
Files: N039W076_AVE_DSM.tif
Size is 3600, 3600
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (-76.000000000000043,40.000000000000028)
Pixel Size = (0.000277777777778,-0.000277777777778)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -76.0000000,  40.0000000) ( 76d 0' 0.00"W, 40d 0' 0.00"N)
Lower Left  ( -76.0000000,  39.0000000) ( 76d 0' 0.00"W, 39d 0' 0.00"N)
Upper Right ( -75.0000000,  40.0000000) ( 75d 0' 0.00"W, 40d 0' 0.00"N)
Lower Right ( -75.0000000,  39.0000000) ( 75d 0' 0.00"W, 39d 0' 0.00"N)
Center      ( -75.5000000,  39.5000000) ( 75d30' 0.00"W, 39d30' 0.00"N)
Band 1 Block=3600x1 Type=Int16, ColorInterp=Gray
```

![image](https://user-images.githubusercontent.com/4528088/53565692-69d25c00-3b5a-11e9-8f72-a0e72114b4cd.png)

**Comment by pierreduf** [comment]
OK that was because the file must be converted in the SRTM/HGT format which is specific and I had trouble converting it because the HGT format is not a 3600x3600 matrix but 3601x3601 one (it seems that one line is added for the overlap with the next cell).

So I managed to get it work by extending to 3601 + making a conversion:

`gdalwarp -of Gtiff -srcnodata 32767 -ts 3601 3601 N041W075_AVE_DSM.tif tmp.tif`

`gdal_translate -of SRTMHGT tmp.tif N41W075.hgt`

But the output coverage is really "scattered" and dotted. Don't know if that's normal or not

![image](https://user-images.githubusercontent.com/4528088/53567454-963ca700-3b5f-11e9-8f12-b3296705945e.png)

**Comment by Cloud-RF** [comment]
I'm pleased you're making progress but this has deviated from the MODIS import issue into a support thread about processing different raster data with GDAL so I'm closing this issue now.
