### ISSUE TITLE
I want to know how to generate a .sdf tiles from DEM image

### ISSUE THREAD

**Issue by Ahmedgis** [Cloud-RF/Signal-Server#2]
From the Readme file in the signal server v2.41

 -- Signal Server 2.41 --
	Compiled for 64 tiles at 1200 pixels/degree
        -d Directory containing .sdf tiles

I want to know how to generate a .sdf tiles from DEM (Digital Elevation Model) image .tif.

Thanks

**Comment by Cloud-RF** [comment]
gdal_translate will convert .tif to .hgt
http://osgeo-org.1560.x6.nabble.com/gdal-dev-Aster-tif-files-to-hgt-td3742884.html

Then for .hgt to .sdf use a utility from SPLAT! called 'srtm2sdf':
https://github.com/jmcmellen/splat/blob/master/utils/srtm2sdf.c

**Comment by Ahmedgis** [comment]
Thanks very much for your reply

**Comment by marcusvinicius178** [comment]
> gdal_translate will convert .tif to .hgt http://osgeo-org.1560.x6.nabble.com/gdal-dev-Aster-tif-files-to-hgt-td3742884.html
> 
> Then for .hgt to .sdf use a utility from SPLAT! called 'srtm2sdf': https://github.com/jmcmellen/splat/blob/master/utils/srtm2sdf.c
srtm2sdf -i Grunner.hgt -o Grunner.sdf
*** Error: "-i" does not have the correct extension (.hgt or .bil)
