### ISSUE TITLE
Length(meters/miles) of output ppm

### ISSUE THREAD

**Issue by miltondts** [Cloud-RF/Signal-Server#22]
When signalserver is run with any model except LOS it appears the output PPM has an width and height equal to 2*R. Is this always the case? Why is the LOS profile not like this? How can we know the size of the output in kilometers/miles for LOS profile? 

EDIT: It appears the stdout output are the coordinates of the bounding rectangle. Still curious why sometimes no cropping is done.

**Comment by Cloud-RF** [comment]
PPM cropping is managed by the cropping boolean. You can change the conditions under which this happens within main.cpp
https://github.com/Cloud-RF/Signal-Server/blob/master/main.cc#L1873
