### ISSUE TITLE
Short filename crashes signal-server

### ISSUE THREAD

**Issue by thetacom** [Cloud-RF/Signal-Server#26]
Version: Signal Server 3.21 (Built for 100 DEM tiles at 1200 pixels)

Command Fails:
signalserver -sdf data/sdf -f 446.0 -R 50 -pm 1 -pe 1 -res 600 -ant data/antennas/dipole/DB413-B -lat 51.5 -lon -1.5 -txh 50.0 -rxh 50.0 -o downloads/Test_Plot

Output:
malloc(): corrupted top size

Command Completes:
signalserver -sdf data/sdf -f 446.0 -R 50 -pm 1 -pe 1 -res 600 -ant data/antennas/dipole/DB413-B -lat 51.5 -lon -1.5 -txh 50.0 -rxh 50.0 -o downloads/Test_Plotaa

Output:
|52.224999|-0.336667|50.775001|-2.663333|

The only differences between the two is the length of the output base name.

**Comment by brotherdust** [comment]
I ran into this bug, too. Took me about 10 hours to figure out. lol

**Comment by FarrantAlex** [comment]
Can't recreate this issue on a new Ubuntu Ryzen9 laptop but the [strncpy line](https://github.com/Cloud-RF/Signal-Server/blob/07f882d3ba849c67b978d715660f0c61c14a8c75/src/main.cc#L1287) hasn't been touched for some years, so I'll keep it open for now unless others with different hosts can confirm it's fixed.
It copies 253 bytes into a 255 byte buffer so unless the buffer is occasionally dirty I'm stumped how this fails with a short string.
