### ISSUE TITLE
How to convert Antenna Pattern (*.ant) files to (*.az) & (*.el)

### ISSUE THREAD

**Issue by Ahmedgis** [Cloud-RF/Signal-Server#3]
Kindly i want to know how to convert Antenna Pattern (*.ant) that found on this link
http://web.cloudrf.com/API/antennas/

to the files to (*.az) & (*.el) that Signal Server used to load the antenna pattern (void LoadPAT(char *filename)) or i want to know a way to read the (*.ant) file instead (*.az) & (*.el) files.

Thanks

**Comment by Cloud-RF** [comment]
This is not an issue with the Signal Server program. Closed.

**Comment by Ahmedgis** [comment]
I know this is not issue with the signal server but how to ask you about this??

**Comment by dBitech** [comment]
@Ahmedgis utils for this have been added to the repo.  https://github.com/Cloud-RF/Signal-Server/tree/master/utils/antenna

**Comment by Ahmedgis** [comment]
@dBitech Thanks very much for the utility.

**Comment by mvalenzr** [comment]
According to the script  Signal-Server/utils/antenna/ant2azel.py it seems that it is converting the dB values, you can fing in the ANT file, into a power values by using the function:

def db_to_norm(db):
    return 10**(db/10.)

As stated in splat! and SignalServer documentation, the values used should by amplitudes. Therefore that function should be modified :

def db_to_norm(db):
    return 10**(db/**20**.)

Am I supposing anything wrong?

Thanks in advance and BR.

**Comment by Cloud-RF** [comment]
db/10 is correct as it is a power ratio.

db/20 is for a amplitude ratio.

References:

http://www.sengpielaudio.com/calculator-db.htm

https://www.rapidtables.com/electric/decibel.html#db_power

**Comment by mvalenzr** [comment]
Signal Server is calculating the pattern by using there expressions (for every azimuth and elevation angles):
pattern = az * elevation;

and then the pattern variable es converted into dBs :
pattern = 20.0 * log10(pattern); 

that means that pattern is an amplitude and not a power magnitude. In the end, we have in SignalServer that the pattern is included in the loss variable:
loss -= pattern;

Then, az y elevation (that come from the az and el files) must be amplitudes and not powers.
As I said before, the way to get and amplitude is to modify the python script:
 def db_to_norm(db):
 return 10**(db/*20*.)

The reason for that is that the normalized amplitude and normalized power patterns in dBs are the same.
http://support.huawei.com/huaweiconnect/carrier/en/thread-68551-1-1.html

That post is supported theoretically in these sources:
1º slides 32 and 33 --> https://es.slideshare.net/indikawithanage/5-anten-theorbasics

2º definition of power depending on electric field  page 1 --> http://www2.elo.utfsm.cl/~elo352/biblio/antenas/Lectura%204.pdf

3º definition of f (theta, phi) = field pattern (I mean that f it is the usual name for a pattern function) page 4  --> https://www.acmaustin.com/lecture_notes/antennas.pdf

4º This is the only article I have found in which the author clearly establish a relationship between amplitude and power pattern for a dipole (but it is in Spanish). 
definition Fn(theta,phi) as the normalized power gain --> page 9
F(theta or phi) = (f(theta or phi))^2 --> page 10

10 * log (F(theta or phi)) = 10 * log ((f(theta or phi))^2) 
simplifying
10 * log (F(theta or phi)) = 20 * log (f(theta or phi)) 

F(theta or phi)dB = 10 * log (F(theta or phi)) = 20 * log (f(theta or phi)) 
https://personales.unican.es/perezvr/pdf/ch10st_web.pdf

Therefore with the .ant files you can calculate the normalized power and amplitude. Thats why I think the python should be changed, but I would like to have some feedback.

Thanks in advance and BR.

**Comment by Cloud-RF** [comment]
You are correct, they should all be amplitude (db/20.)

Can you create a pull request?

Alex
