### ISSUE TITLE
SRTM2SDF Line 140  - BIL filetype - Output filename is incorrect

### ISSUE THREAD

**Issue by salSB** [Cloud-RF/Signal-Server#30]
On Line 140 of srtm2sdf.cc in utils/sdf/usgs2sdf

max_north=max_north+1;

Should be min_north+1 (as in other sections) also max_north is always 0 when within "if (bil)" block

Causes filename to become min_north:1:..:....sdf instead of min_north:max_north:...:.....sdf

$ ../srtm2sdf ./n32_w111_3arc_v2.bil
*** Deg_West: -111.000000
*** Deg_North: 33.000000
*** Deg_North: 33.000000
*** Min/Max North: 33 - 0
*** Min/Max North: 33 - 1
Reading ./n32_w111_3arc_v2.bil... 
Writing 33:1:111:112.sdf... Done!

After fix:

$ ../srtm2sdf ./n32_w111_3arc_v2.bil
*** Deg_West: -111.000000
*** Deg_North: 33.000000
*** Deg_North: 33.000000 | 1
*** Min/Max North: 33 - 0
*** Min/Max North: 33 - 34
Reading ./n32_w111_3arc_v2.bil... 
Writing 33:34:111:112.sdf... Done!

**Comment by FarrantAlex** [comment]
Fixed, thanks for reporting.
