### ISSUE TITLE
Center of Output PPM image is White, Not Red, as Indicated by the .dcf File

### ISSUE THREAD

**Issue by butterisgod** [Cloud-RF/Signal-Server#36]
One would assume the center of the plot would have the highest signal intensity, but for some reason the plot is white (or transparent if you're using a PNG). Here's my inputs:
       -sdf path/to/file 
        -color /path/to/file
        -lat 40  # Tx Latitude (decimal degrees)
        -lon -74   # Tx Longitude (decimal degrees)
        -f 3550   # Tx Frequency (MHz)
        -erp 1   # Tx Total Effective Radiated Power (Watts)
        -gc 10     # Random ground clutter (feet/meters)
        -o  xxx   # Output file basename
        -te 1     # Terrain code 1-6
        -ant /path/to/file        # Antenna file
        -dbg             # Debug
        -dbm             # Graphed in Decibels
        -R 1       # Radius
        -res 2400     # Resolution
        -pm 1         # Propagation Model
        -pe 2         # Propagation model mode: 1=Urban,2=Suburban,3=Rural
        -txh 20  # Antenna height
        -rxh 3        # Receiver Height
        -rt -65       # Decibel Cutoff
![Screenshot from 2023-05-26 04-55-58](https://github.com/Cloud-RF/Signal-Server/assets/67658949/94cdcbd4-7061-44cd-808f-65492de2dc1c)

**Comment by butterisgod** [comment]
Upon closer inspection it seems like the issue isn't bad for the larger resolutions, but at higher frequencies like 3.5ghz and it's lower propagation characteristics, this 'white" spot in the center can encompass 50% of the coverage area.

**Comment by FarrantAlex** [comment]
Colours are defined in your colour key. If you don't define them, they're undefined.
